#!/usr/bin/env bash
# script that configures a new Ubuntu machine to install
# nginx using listening port 80 that returns a page that
# contains the string `Hello World` when querying at its
# root `/`.

echo -e "Updating and doing some minor checks...\n"

# Function to install a package if not already installed
install() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "${1} is already installed.\n"
    fi
}

install nginx # Install nginx

echo -e "\nSetting up some minor stuff.\n"

# Allowing nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
website_dir="/var/www"
if [ -d "$website_dir" ]; then
    sudo chown -R "$USER":"$USER" "$website_dir"
    sudo chmod -R 755 "$website_dir"
else
    sudo mkdir -p "$website_dir"
    sudo chown -R "$USER":"$USER" "$website_dir"
    sudo chmod -R 755 "$website_dir"
fi

# Create directories if not present
for dir in "$website_dir"/{html,error}; do
    [ -d "$dir" ] || mkdir -p "$dir"
done

# Create a new index file
echo "Hello World!" > "$website_dir"/html/index.html

# Create a new error page
echo "Ceci n'est pas une page" > "$website_dir"/html/error_404.html

# Backup default server config file
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

server_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://youtube.com permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}"

echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

if ! pgrep -x nginx > /dev/null; then
    sudo service nginx start
else
    sudo service nginx restart
fi
