#!/usr/bin/env bash
#script shows numbers to 20 and bad luck at certain positions
i=0
while [ $i -lt 20 ] 
do
	echo $((i + 1))
	case $i in
		3)
			echo "bad luck from China"
			;;
		8)
			echo "bad luck from Japan"
			;;
		16)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac
	i=$(( i + 1))	
done                                    
