#!/usr/bin/env bash
#script shows numbers to 20 and bad luck at certain positions
for ((i=0;i<20;i++)); 
do
	echo $((i + 1))
	case $i in
		3)
			echo "bad luck from China"
			;;
		8)
			echo "bad luck from Japan"
			;;
		16)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac 
done
~                                                    
