#!/usr/bin/env bash
# script to configure broken container to work with nginx at port 8080

pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
# restart nginx as nginx user
sudo -u nginx service nginx restart
